// <auto-generated />
using System;
using HS4_Dergi_Web_Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HS4_Dergi_Web_Api.Migrations
{
    [DbContext(typeof(JournalDBContext))]
    partial class JournalDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HS4_Dergi_Web_Api.Models.Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JournalSeriesId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("JournalSeriesId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 12,
                            Description = "Internal",
                            JournalSeriesId = 9,
                            Title = "Corporate Directives Manager"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 9,
                            Description = "District",
                            JournalSeriesId = 14,
                            Title = "Future Group Planner"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 15,
                            Description = "Lead",
                            JournalSeriesId = 5,
                            Title = "Chief Identity Assistant"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 8,
                            Description = "Corporate",
                            JournalSeriesId = 19,
                            Title = "Dynamic Creative Supervisor"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 12,
                            Description = "Product",
                            JournalSeriesId = 1,
                            Title = "District Configuration Coordinator"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 3,
                            Description = "Dynamic",
                            JournalSeriesId = 1,
                            Title = "Senior Brand Executive"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 20,
                            Description = "Customer",
                            JournalSeriesId = 3,
                            Title = "Dynamic Operations Engineer"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 20,
                            Description = "Principal",
                            JournalSeriesId = 20,
                            Title = "Global Accountability Administrator"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 17,
                            Description = "Dynamic",
                            JournalSeriesId = 14,
                            Title = "Corporate Optimization Executive"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 9,
                            Description = "Product",
                            JournalSeriesId = 14,
                            Title = "Principal Program Consultant"
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 8,
                            Description = "Customer",
                            JournalSeriesId = 7,
                            Title = "Lead Usability Facilitator"
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 17,
                            Description = "Forward",
                            JournalSeriesId = 5,
                            Title = "Global Mobility Manager"
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 13,
                            Description = "Human",
                            JournalSeriesId = 11,
                            Title = "Principal Security Facilitator"
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 4,
                            Description = "District",
                            JournalSeriesId = 2,
                            Title = "Global Applications Agent"
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 4,
                            Description = "District",
                            JournalSeriesId = 2,
                            Title = "Chief Group Manager"
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 11,
                            Description = "Customer",
                            JournalSeriesId = 1,
                            Title = "Future Factors Executive"
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 9,
                            Description = "Senior",
                            JournalSeriesId = 4,
                            Title = "Future Metrics Analyst"
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 14,
                            Description = "Human",
                            JournalSeriesId = 16,
                            Title = "Legacy Identity Developer"
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 15,
                            Description = "Product",
                            JournalSeriesId = 20,
                            Title = "Forward Security Administrator"
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 13,
                            Description = "Forward",
                            JournalSeriesId = 20,
                            Title = "Forward Communications Consultant"
                        });
                });

            modelBuilder.Entity("HS4_Dergi_Web_Api.Models.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Monique Lakin"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Cristina Mills"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Emmet Gerlach"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Enrique Kiehn"
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Elmer Mann"
                        },
                        new
                        {
                            Id = 6,
                            FullName = "Alda Bradtke"
                        },
                        new
                        {
                            Id = 7,
                            FullName = "Alice Jones"
                        },
                        new
                        {
                            Id = 8,
                            FullName = "Marjolaine Reichel"
                        },
                        new
                        {
                            Id = 9,
                            FullName = "Obie Windler"
                        },
                        new
                        {
                            Id = 10,
                            FullName = "Georgiana Balistreri"
                        },
                        new
                        {
                            Id = 11,
                            FullName = "Winfield Davis"
                        },
                        new
                        {
                            Id = 12,
                            FullName = "Jeremie Miller"
                        },
                        new
                        {
                            Id = 13,
                            FullName = "Jerel Bergnaum"
                        },
                        new
                        {
                            Id = 14,
                            FullName = "Melany Kub"
                        },
                        new
                        {
                            Id = 15,
                            FullName = "Robbie Tromp"
                        },
                        new
                        {
                            Id = 16,
                            FullName = "Julio Harber"
                        },
                        new
                        {
                            Id = 17,
                            FullName = "Morgan Abernathy"
                        },
                        new
                        {
                            Id = 18,
                            FullName = "Marlen O'Conner"
                        },
                        new
                        {
                            Id = 19,
                            FullName = "Karley Kovacek"
                        },
                        new
                        {
                            Id = 20,
                            FullName = "Dolores Rodriguez"
                        });
                });

            modelBuilder.Entity("HS4_Dergi_Web_Api.Models.Entities.Journal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Concessionaire")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("JournalType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PublisherId");

                    b.ToTable("Journals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Concessionaire = "Gus Wyman",
                            JournalType = 6,
                            Name = "Aniya",
                            Period = 2,
                            PublisherId = 6
                        },
                        new
                        {
                            Id = 2,
                            Concessionaire = "Brenden Mraz",
                            JournalType = 1,
                            Name = "Sasha",
                            Period = 4,
                            PublisherId = 19
                        },
                        new
                        {
                            Id = 3,
                            Concessionaire = "Adolf Dickinson",
                            JournalType = 2,
                            Name = "Foster",
                            Period = 4,
                            PublisherId = 3
                        },
                        new
                        {
                            Id = 4,
                            Concessionaire = "Marguerite Spencer",
                            JournalType = 6,
                            Name = "Adriel",
                            Period = 3,
                            PublisherId = 10
                        },
                        new
                        {
                            Id = 5,
                            Concessionaire = "Cordelia Mayer",
                            JournalType = 5,
                            Name = "Odie",
                            Period = 4,
                            PublisherId = 15
                        },
                        new
                        {
                            Id = 6,
                            Concessionaire = "Kiana Howell",
                            JournalType = 5,
                            Name = "Stacey",
                            Period = 1,
                            PublisherId = 3
                        },
                        new
                        {
                            Id = 7,
                            Concessionaire = "Michale Anderson",
                            JournalType = 5,
                            Name = "Ruthe",
                            Period = 5,
                            PublisherId = 5
                        },
                        new
                        {
                            Id = 8,
                            Concessionaire = "Lavern Hyatt",
                            JournalType = 2,
                            Name = "Harold",
                            Period = 5,
                            PublisherId = 14
                        },
                        new
                        {
                            Id = 9,
                            Concessionaire = "Kory Turcotte",
                            JournalType = 4,
                            Name = "Imogene",
                            Period = 3,
                            PublisherId = 12
                        },
                        new
                        {
                            Id = 10,
                            Concessionaire = "Baron Spencer",
                            JournalType = 4,
                            Name = "Ike",
                            Period = 1,
                            PublisherId = 4
                        },
                        new
                        {
                            Id = 11,
                            Concessionaire = "Amber Johns",
                            JournalType = 6,
                            Name = "Marilyne",
                            Period = 2,
                            PublisherId = 2
                        },
                        new
                        {
                            Id = 12,
                            Concessionaire = "Kade Schuster",
                            JournalType = 1,
                            Name = "Kareem",
                            Period = 3,
                            PublisherId = 1
                        },
                        new
                        {
                            Id = 13,
                            Concessionaire = "Darrell Stanton",
                            JournalType = 4,
                            Name = "Bette",
                            Period = 3,
                            PublisherId = 20
                        },
                        new
                        {
                            Id = 14,
                            Concessionaire = "Judy Goldner",
                            JournalType = 6,
                            Name = "Anthony",
                            Period = 2,
                            PublisherId = 3
                        },
                        new
                        {
                            Id = 15,
                            Concessionaire = "Garrett Corkery",
                            JournalType = 6,
                            Name = "Rogers",
                            Period = 2,
                            PublisherId = 2
                        },
                        new
                        {
                            Id = 16,
                            Concessionaire = "Eunice Medhurst",
                            JournalType = 5,
                            Name = "Eloisa",
                            Period = 1,
                            PublisherId = 16
                        },
                        new
                        {
                            Id = 17,
                            Concessionaire = "Kacie Hermiston",
                            JournalType = 2,
                            Name = "Renee",
                            Period = 4,
                            PublisherId = 9
                        },
                        new
                        {
                            Id = 18,
                            Concessionaire = "Grant Collins",
                            JournalType = 6,
                            Name = "Sallie",
                            Period = 3,
                            PublisherId = 4
                        },
                        new
                        {
                            Id = 19,
                            Concessionaire = "Roger Lubowitz",
                            JournalType = 6,
                            Name = "Mayra",
                            Period = 3,
                            PublisherId = 12
                        },
                        new
                        {
                            Id = 20,
                            Concessionaire = "Paris Pacocha",
                            JournalType = 2,
                            Name = "Taylor",
                            Period = 1,
                            PublisherId = 18
                        });
                });

            modelBuilder.Entity("HS4_Dergi_Web_Api.Models.Entities.JournalSeries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Editor")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("JournalId")
                        .HasColumnType("int");

                    b.Property<int>("Page")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasMaxLength(4)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("JournalId");

                    b.ToTable("JournalSeries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Editor = "Terrill Quigley",
                            JournalId = 15,
                            Page = 40,
                            Price = 10m,
                            PublicationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Editor = "Myrna Braun",
                            JournalId = 6,
                            Page = 60,
                            Price = 10m,
                            PublicationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Editor = "Brennon Bins",
                            JournalId = 1,
                            Page = 85,
                            Price = 10m,
                            PublicationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Editor = "Leonora Ritchie",
                            JournalId = 18,
                            Page = 88,
                            Price = 10m,
                            PublicationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Editor = "Alexa Wuckert",
                            JournalId = 20,
                            Page = 30,
                            Price = 10m,
                            PublicationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Editor = "Vivianne Wilkinson",
                            JournalId = 11,
                            Page = 39,
                            Price = 10m,
                            PublicationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Editor = "Kameron Kertzmann",
                            JournalId = 20,
                            Page = 93,
                            Price = 10m,
                            PublicationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Editor = "Sylvia Haley",
                            JournalId = 11,
                            Page = 37,
                            Price = 10m,
                            PublicationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Editor = "Jeramy Kulas",
                            JournalId = 20,
                            Page = 59,
                            Price = 10m,
                            PublicationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Editor = "Deonte Cole",
                            JournalId = 1,
                            Page = 76,
                            Price = 10m,
                            PublicationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            Editor = "Isidro Carroll",
                            JournalId = 13,
                            Page = 34,
                            Price = 10m,
                            PublicationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            Editor = "Angela Lesch",
                            JournalId = 15,
                            Page = 48,
                            Price = 10m,
                            PublicationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            Editor = "Oliver Bayer",
                            JournalId = 14,
                            Page = 83,
                            Price = 10m,
                            PublicationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            Editor = "Dwight Block",
                            JournalId = 20,
                            Page = 93,
                            Price = 10m,
                            PublicationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            Editor = "Kiley Mills",
                            JournalId = 7,
                            Page = 43,
                            Price = 10m,
                            PublicationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            Editor = "Crawford Kemmer",
                            JournalId = 17,
                            Page = 57,
                            Price = 10m,
                            PublicationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            Editor = "Walton Feil",
                            JournalId = 3,
                            Page = 67,
                            Price = 10m,
                            PublicationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            Editor = "Eric Shields",
                            JournalId = 18,
                            Page = 73,
                            Price = 10m,
                            PublicationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            Editor = "Emmalee Wisozk",
                            JournalId = 18,
                            Page = 66,
                            Price = 10m,
                            PublicationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            Editor = "Skylar Kuvalis",
                            JournalId = 1,
                            Page = 64,
                            Price = 10m,
                            PublicationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HS4_Dergi_Web_Api.Models.Entities.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Buddy Heathcote"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Juwan Becker"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Gabrielle Effertz"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Zora Gutkowski"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Jessika Welch"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Joannie Goldner"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Jacques Miller"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Geoffrey Lockman"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Adonis Morissette"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Bernardo Gerhold"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Katrine Spencer"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Lempi Jakubowski"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Alicia Predovic"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Gabe Barton"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Myah Bartoletti"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Chadrick Gulgowski"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Maudie Nienow"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Shany Nikolaus"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Lynn Kiehn"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Danika Grady"
                        });
                });

            modelBuilder.Entity("HS4_Dergi_Web_Api.Models.Entities.Article", b =>
                {
                    b.HasOne("HS4_Dergi_Web_Api.Models.Entities.Author", "Author")
                        .WithMany("Articles")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HS4_Dergi_Web_Api.Models.Entities.JournalSeries", "JournalSeries")
                        .WithMany("Articles")
                        .HasForeignKey("JournalSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("JournalSeries");
                });

            modelBuilder.Entity("HS4_Dergi_Web_Api.Models.Entities.Journal", b =>
                {
                    b.HasOne("HS4_Dergi_Web_Api.Models.Entities.Publisher", "Publisher")
                        .WithMany("Journals")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("HS4_Dergi_Web_Api.Models.Entities.JournalSeries", b =>
                {
                    b.HasOne("HS4_Dergi_Web_Api.Models.Entities.Journal", "Journal")
                        .WithMany("JournalSeries")
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journal");
                });

            modelBuilder.Entity("HS4_Dergi_Web_Api.Models.Entities.Author", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("HS4_Dergi_Web_Api.Models.Entities.Journal", b =>
                {
                    b.Navigation("JournalSeries");
                });

            modelBuilder.Entity("HS4_Dergi_Web_Api.Models.Entities.JournalSeries", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("HS4_Dergi_Web_Api.Models.Entities.Publisher", b =>
                {
                    b.Navigation("Journals");
                });
#pragma warning restore 612, 618
        }
    }
}
